apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/primitives/namespace
  - cnpg-secret.yml
  - cnpg-cluster.yml
  - lightrag-db.yml
  - lightrag-dev-db.yml
  - nodeport-service.yml

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: cnpg-cluster
      - op: replace
        path: /metadata/labels/name
        value: cnpg-cluster
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1component
        value: database
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1part-of
        value: lightrag
