apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/primitives/namespace
  - redis.yml

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: lightrag
      - op: replace
        path: /metadata/labels/name
        value: lightrag
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1component
        value: cache
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1part-of
        value: lightrag
